### ISSUE TITLE
Invalid route type o*e1

### ISSUE THREAD

**Issue by dietybright** [dainok/netdoc#117]
Hi @dainok ,

Kindly help to add o*e1 as ospf type as below error on our device

An exception occurred: ValueError: Invalid route type o*e1

Traceback (most recent call last):
  File "/opt/netbox/netbox/extras/scripts.py", line 504, in _run_script
    script.output = script.run(data=data, commit=commit)
  File "/opt/netbox/netbox/scripts/netdoc_scripts.py", line 357, in run
    log_ingest(log)
  File "/opt/netbox/venv/lib/python3.10/site-packages/netdoc/utils.py", line 399, in log_ingest
    module.ingest(log)
  File "/opt/netbox/venv/lib/python3.10/site-packages/netdoc/ingestors/netmiko_cisco_xr_show_route.py", line 33, in ingest
    protocol = utils.normalize_route_type(item.get("protocol"))
  File "/opt/netbox/venv/lib/python3.10/site-packages/netdoc/utils.py", line 825, in normalize_route_type
    raise ValueError(f"Invalid route type {route_type}")
ValueError: Invalid route type o*e1

**Comment by dainok** [comment]
Test #118

**Comment by dietybright** [comment]
It fixed, thank @dainok
