### ISSUE TITLE
Build errors on Docker Netbox v3.5-2.6.1 with Netdoc 3.5.10 and higher

### ISSUE THREAD

**Issue by Cennepal** [dainok/netdoc#130]
Hello,

I'm currently using Netbox Docker with Netbox being on version 3.5.9. While trying to install it with NetDoc I stumbled onto the following build error:

```
 > [9/9] RUN SECRET_KEY="dummydummydummydummydummydummydummydummydummydummy" /opt/netbox/venv/bin/python /opt/netbox/netbox/manage.py collectstatic --no-input:
#0 0.333 🧬 loaded config '/etc/netbox/config/configuration.py'
#0 0.334 🧬 loaded config '/etc/netbox/config/extra.py'
#0 0.334 🧬 loaded config '/etc/netbox/config/logging.py'
#0 0.334 🧬 loaded config '/etc/netbox/config/plugins.py'
#0 1.430 Traceback (most recent call last):
#0 1.430   File "/opt/netbox/venv/lib/python3.10/site-packages/django/db/backends/base/base.py", line 282, in ensure_connection
#0 1.431     self.connect()
#0 1.431   File "/opt/netbox/venv/lib/python3.10/site-packages/django/utils/asyncio.py", line 26, in inner
#0 1.431     return func(*args, **kwargs)
#0 1.431   File "/opt/netbox/venv/lib/python3.10/site-packages/django/db/backends/base/base.py", line 263, in connect
#0 1.431     self.connection = self.get_new_connection(conn_params)
#0 1.431   File "/opt/netbox/venv/lib/python3.10/site-packages/django/utils/asyncio.py", line 26, in inner
#0 1.431     return func(*args, **kwargs)
#0 1.431   File "/opt/netbox/venv/lib/python3.10/site-packages/django/db/backends/postgresql/base.py", line 215, in get_new_connection
#0 1.431     connection = Database.connect(**conn_params)
#0 1.431   File "/opt/netbox/venv/lib/python3.10/site-packages/psycopg2/__init__.py", line 122, in connect
#0 1.431     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
#0 1.431 psycopg2.OperationalError: connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
#0 1.432        Is the server running on that host and accepting TCP/IP connections?
#0 1.432 connection to server at "localhost" (::1), port 5432 failed: Cannot assign requested address
#0 1.432        Is the server running on that host and accepting TCP/IP connections?
#0 1.432
#0 1.432
#0 1.432 The above exception was the direct cause of the following exception:
#0 1.432
#0 1.432 Traceback (most recent call last):
#0 1.432   File "/opt/netbox/netbox/manage.py", line 10, in <module>
#0 1.432     execute_from_command_line(sys.argv)
#0 1.432   File "/opt/netbox/venv/lib/python3.10/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
#0 1.432     utility.execute()
#0 1.432   File "/opt/netbox/venv/lib/python3.10/site-packages/django/core/management/__init__.py", line 420, in execute
#0 1.432     django.setup()
#0 1.432   File "/opt/netbox/venv/lib/python3.10/site-packages/django/__init__.py", line 24, in setup
#0 1.433     apps.populate(settings.INSTALLED_APPS)
#0 1.433   File "/opt/netbox/venv/lib/python3.10/site-packages/django/apps/registry.py", line 124, in populate
#0 1.433     app_config.ready()
#0 1.433   File "/opt/netbox/venv/lib/python3.10/site-packages/netdoc/__init__.py", line 64, in ready
#0 1.433     jobs_ds_o = DataSource.objects.get(name="netdoc_jobs")
#0 1.433   File "/opt/netbox/venv/lib/python3.10/site-packages/django/db/models/manager.py", line 85, in manager_method
#0 1.433     return getattr(self.get_queryset(), name)(*args, **kwargs)
#0 1.433   File "/opt/netbox/venv/lib/python3.10/site-packages/django/db/models/query.py", line 646, in get
#0 1.434     num = len(clone)
#0 1.434   File "/opt/netbox/venv/lib/python3.10/site-packages/django/db/models/query.py", line 376, in __len__
#0 1.434     self._fetch_all()
#0 1.434   File "/opt/netbox/venv/lib/python3.10/site-packages/django/db/models/query.py", line 1867, in _fetch_all
#0 1.434     self._result_cache = list(self._iterable_class(self))
#0 1.434   File "/opt/netbox/venv/lib/python3.10/site-packages/django/db/models/query.py", line 87, in __iter__
#0 1.434     results = compiler.execute_sql(
#0 1.435   File "/opt/netbox/venv/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1396, in execute_sql
#0 1.435     cursor = self.connection.cursor()
#0 1.435   File "/opt/netbox/venv/lib/python3.10/site-packages/django/utils/asyncio.py", line 26, in inner
#0 1.435     return func(*args, **kwargs)
#0 1.435   File "/opt/netbox/venv/lib/python3.10/site-packages/django/db/backends/base/base.py", line 323, in cursor
#0 1.435     return self._cursor()
#0 1.435   File "/opt/netbox/venv/lib/python3.10/site-packages/django/db/backends/base/base.py", line 299, in _cursor
#0 1.436     self.ensure_connection()
#0 1.436   File "/opt/netbox/venv/lib/python3.10/site-packages/django/utils/asyncio.py", line 26, in inner
#0 1.436     return func(*args, **kwargs)
#0 1.436   File "/opt/netbox/venv/lib/python3.10/site-packages/django/db/backends/base/base.py", line 281, in ensure_connection
#0 1.436     with self.wrap_database_errors:
#0 1.436   File "/opt/netbox/venv/lib/python3.10/site-packages/django/db/utils.py", line 91, in __exit__
#0 1.436     raise dj_exc_value.with_traceback(traceback) from exc_value
#0 1.436   File "/opt/netbox/venv/lib/python3.10/site-packages/django/db/backends/base/base.py", line 282, in ensure_connection
#0 1.437     self.connect()
#0 1.437   File "/opt/netbox/venv/lib/python3.10/site-packages/django/utils/asyncio.py", line 26, in inner
#0 1.437     return func(*args, **kwargs)
#0 1.437   File "/opt/netbox/venv/lib/python3.10/site-packages/django/db/backends/base/base.py", line 263, in connect
#0 1.437     self.connection = self.get_new_connection(conn_params)
#0 1.437   File "/opt/netbox/venv/lib/python3.10/site-packages/django/utils/asyncio.py", line 26, in inner
#0 1.437     return func(*args, **kwargs)
#0 1.437   File "/opt/netbox/venv/lib/python3.10/site-packages/django/db/backends/postgresql/base.py", line 215, in get_new_connection
#0 1.438     connection = Database.connect(**conn_params)
#0 1.438   File "/opt/netbox/venv/lib/python3.10/site-packages/psycopg2/__init__.py", line 122, in connect
#0 1.438     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
#0 1.438 django.db.utils.OperationalError: connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
#0 1.438        Is the server running on that host and accepting TCP/IP connections?
#0 1.438 connection to server at "localhost" (::1), port 5432 failed: Cannot assign requested address
#0 1.438        Is the server running on that host and accepting TCP/IP connections?
#0 1.438
------
failed to solve: executor failed running [/bin/sh -c SECRET_KEY="dummydummydummydummydummydummydummydummydummydummy" /opt/netbox/venv/bin/python /opt/netbox/netbox/manage.py collectstatic --no-input]: exit code: 1
```

I slowly worked my way down from version 3.5.21 until 3.5.9 finally worked. I'm honestly quite clueless about the postgres error, so not much I can help. Just wanted to share.

**Comment by Cennepal** [comment]
I also checked with netbox 3.5.8, still the same. Gonna install netbox in a non docker environment and see if that works.

**Comment by dainok** [comment]
Hi! The error is pretty explanatory:

```text
psycopg2.OperationalError: connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
#0 1.432        Is the server running on that host and accepting TCP/IP connections?
```

Postgres is not running on localhost. But... you are using contaienrs, so you should have a separated container providing the database service. You won't, I guess, run everything from a single container.

See:

```
https://github.com/dainok/netdoc/blob/master/docker/configuration/configuration.py
```

`DB_HOST` should be defined, and fallback to localhost which won't work because postgres is not supposed to run in the same container (unless you customeze your docker compose)

**Comment by Cennepal** [comment]
That was the first thing I tried, I also tried exposing the ports on the postgres container and managed to connect to it with psql on my host, but I still got the same error when building on docker. NetDoc 3.5.10 still builds, but everything after that throws this error.

**Comment by Cennepal** [comment]
Also, netbox docker already splits up itself into containers, but that doesn't really matter for the build process. However, I still tried using the IP of the would-be-postgres container, but it just took longer to timeout until I got the same error.

**Comment by dainok** [comment]
Sorry but this is about running Netbox on Docker. It has nothing to do with NetDoc.

**Comment by Cennepal** [comment]
Then I'll just stick to 3.5.10. Thanks for your time.
