### ISSUE TITLE
Vmware Pyvmomo ingest mac-address 'None' cannot be parsed 

### ISSUE THREAD

**Issue by dietybright** [dainok/netdoc#132]
```
An exception occurred: ValueError: 'None' cannot be parsed as EUI48

Traceback (most recent call last):
  File "/opt/netbox/netbox/extras/scripts.py", line 504, in _run_script
    script.output = script.run(data=data, commit=commit)
  File "/opt/netbox/netbox/scripts/netdoc_scripts.py", line 357, in run
    log_ingest(log)
  File "/opt/netbox/venv/lib/python3.10/site-packages/netdoc/utils.py", line 407, in log_ingest
    module.ingest(log)
  File "/opt/netbox/venv/lib/python3.10/site-packages/netdoc/ingestors/json_vmware_vsphere_pyvmomi.py", line 110, in ingest
    utils.normalize_mac_address(nic.get("mac_address"))
  File "/opt/netbox/venv/lib/python3.10/site-packages/netdoc/utils.py", line 710, in normalize_mac_address
    mac_address_o = macaddress.MAC(mac_address)
  File "/opt/netbox/venv/lib/python3.10/site-packages/macaddress.py", line 106, in __init__
    self._address, _ = _parse(address, type(self))
  File "/opt/netbox/venv/lib/python3.10/site-packages/macaddress.py", line 385, in _parse
    raise _value_error(string, 'cannot be parsed as', *classes)
ValueError: 'None' cannot be parsed as EUI48
```

Change else None > "00:00:00:00:00:00" fixed the issue
/opt/netbox/venv/lib/python3.10/site-packages/netdoc/ingestors/json_vmware_vsphere_pyvmomi.py
```
        for nic in host.get("nics").values():
            interface_name = nic.get("name")
            label = utils.normalize_interface_label(interface_name)
            mac_address = (
                utils.normalize_mac_address(nic.get("mac_address"))
                if not utils.incomplete_mac(nic.get("mac_address"))
                else None
                else "00:00:00:00:00:00"
```

**Comment by dainok** [comment]
Thank you @dietybright . Honestly this is surprising: how can a nic exist without a MAC address? Should we ingest it or just skip?

**Comment by dietybright** [comment]
Hi @dainok , I think we should ingest it with mac "00:00:00:00:00:00"
