### ISSUE TITLE
Plugin doesn't run when /opt/netbox/netbox/nornir.log is not writeable

### ISSUE THREAD

**Issue by jaannnis** [dainok/netdoc#18]
Hi,

if the file /opt/netbox/netbox/nornir.log is not writeable by the user netbox is running, discovery doesn't work.

Output in  `/var/log/messages`
(also I'm running 3.4Beta1 if this makes a difference)
```
Nov 23 18:03:05 itsrv3066 python3[220818]: Traceback (most recent call last):
Nov 23 18:03:05 itsrv3066 python3[220818]:  File "/opt/netbox/venv/lib64/python3.9/site-packages/rq/worker.py", line 1075, in perform_job
Nov 23 18:03:05 itsrv3066 python3[220818]:    rv = job.perform()
Nov 23 18:03:05 itsrv3066 python3[220818]:  File "/opt/netbox/venv/lib64/python3.9/site-packages/rq/job.py", line 854, in perform
Nov 23 18:03:05 itsrv3066 python3[220818]:    self._result = self._execute()
Nov 23 18:03:05 itsrv3066 python3[220818]:  File "/opt/netbox/venv/lib64/python3.9/site-packages/rq/job.py", line 877, in _execute
Nov 23 18:03:05 itsrv3066 python3[220818]:    result = self.func(*self.args, **self.kwargs)
Nov 23 18:03:05 itsrv3066 python3[220818]:  File "/opt/netbox/venv/lib64/python3.9/site-packages/netdoc/tasks.py", line 33, in discovery
Nov 23 18:03:05 itsrv3066 python3[220818]:    fh = logging.FileHandler(f"{settings.BASE_DIR}/nornir.log")
Nov 23 18:03:05 itsrv3066 python3[220818]:  File "/usr/lib64/python3.9/logging/__init__.py", line 1146, in __init__
Nov 23 18:03:05 itsrv3066 python3[220818]:    StreamHandler.__init__(self, self._open())
Nov 23 18:03:05 itsrv3066 python3[220818]:  File "/usr/lib64/python3.9/logging/__init__.py", line 1175, in _open
Nov 23 18:03:05 itsrv3066 python3[220818]:    return open(self.baseFilename, self.mode, encoding=self.encoding,
Nov 23 18:03:05 itsrv3066 python3[220818]: PermissionError: [Errno 13] Permission denied: '/opt/netbox-3.4-beta1/netbox/nornir.log'
Nov 23 18:03:05 itsrv3066 python3[220818]: Traceback (most recent call last):
Nov 23 18:03:05 itsrv3066 python3[220818]:  File "/opt/netbox/venv/lib64/python3.9/site-packages/rq/worker.py", line 1075, in perform_job
Nov 23 18:03:05 itsrv3066 python3[220818]:    rv = job.perform()
Nov 23 18:03:05 itsrv3066 python3[220818]:  File "/opt/netbox/venv/lib64/python3.9/site-packages/rq/job.py", line 854, in perform
Nov 23 18:03:05 itsrv3066 python3[220818]:    self._result = self._execute()
Nov 23 18:03:05 itsrv3066 python3[220818]:  File "/opt/netbox/venv/lib64/python3.9/site-packages/rq/job.py", line 877, in _execute
Nov 23 18:03:05 itsrv3066 python3[220818]:    result = self.func(*self.args, **self.kwargs)
Nov 23 18:03:05 itsrv3066 python3[220818]:  File "/opt/netbox/venv/lib64/python3.9/site-packages/netdoc/tasks.py", line 33, in discovery
Nov 23 18:03:05 itsrv3066 python3[220818]:    fh = logging.FileHandler(f"{settings.BASE_DIR}/nornir.log")
Nov 23 18:03:05 itsrv3066 python3[220818]:  File "/usr/lib64/python3.9/logging/__init__.py", line 1146, in __init__
Nov 23 18:03:05 itsrv3066 python3[220818]:    StreamHandler.__init__(self, self._open())
Nov 23 18:03:05 itsrv3066 python3[220818]:  File "/usr/lib64/python3.9/logging/__init__.py", line 1175, in _open
Nov 23 18:03:05 itsrv3066 python3[220818]:    return open(self.baseFilename, self.mode, encoding=self.encoding,
Nov 23 18:03:05 itsrv3066 python3[220818]: PermissionError: [Errno 13] Permission denied: '/opt/netbox-3.4-beta1/netbox/nornir.log'
```

Workaround:
touch /opt/netbox/netbox/nornir.log && chown $netbox-user:$netbox-group /opt/netbox/netbox/nornir.log 

Better solution probably would be to write the log somewhere else?

**Comment by dainok** [comment]
This should have been fixed in https://github.com/dainok/netdoc/issues/4 Can you please check?

**Comment by jaannnis** [comment]
I have 0.9.8 installed via pip:
```
Name: netdoc
Version: 0.9.8
Summary: Network Documentation plugin for NetBox
Home-page: https://github.com/dainok/netdoc
Author: Andrea Dainese
Author-email: andrea.dainese@pm.me
License: GNU v3.0
Location: /opt/netbox-3.4-beta1/venv/lib/python3.9/site-packages
Requires: ipaddress, macaddress, nornir, nornir-netmiko, nornir-utils, ouilookup, python-slugify
Required-by: 
```

This should be included, right?
But there are many bugs with this plugin and the Beta of NetBox I'm running, so this can of course be the issue of this also. Feel free to close if not relevant for you!

**Comment by mhabiballa** [comment]
I've the exact same error after upgrading netbox to 3.3.9!.
`netbox@888:/opt/netbox$ journalctl -u netbox-rq -f
Dec 05 11:53:13 ipam python3[19435]:     self._result = self._execute()
Dec 05 11:53:13 ipam python3[19435]:   File "/opt/netbox/venv/lib/python3.10/site-packages/rq/job.py", line 877, in _execute
Dec 05 11:53:13 ipam python3[19435]:     result = self.func(*self.args, **self.kwargs)
Dec 05 11:53:13 ipam python3[19435]:   File "/opt/netbox/venv/lib/python3.10/site-packages/netdoc/tasks.py", line 33, in discovery
Dec 05 11:53:13 ipam python3[19435]:     fh = logging.FileHandler(f"{settings.BASE_DIR}/nornir.log")
Dec 05 11:53:13 ipam python3[19435]:   File "/usr/lib/python3.10/logging/__init__.py", line 1169, in __init__
Dec 05 11:53:13 ipam python3[19435]:     StreamHandler.__init__(self, self._open())
Dec 05 11:53:13 ipam python3[19435]:   File "/usr/lib/python3.10/logging/__init__.py", line 1201, in _open
Dec 05 11:53:13 ipam python3[19435]:     return open_func(self.baseFilename, self.mode,
Dec 05 11:53:13 ipam python3[19435]: PermissionError: [Errno 13] Permission denied: '/opt/netbox-3.3.9/netbox/nornir.log'`

**Comment by dainok** [comment]
Now you can configure NORNIR_LOG option (see README.md).
