### ISSUE TITLE
ingest error

### ISSUE THREAD

**Issue by mamingzhi945** [dainok/netdoc#24]
mode：netmiko_cisco_nxos

```


4 | Info | Ingesting log 1455 with command show lldp neighbors detail on device 10.254.23.3 via netmiko_cisco_nxos
-- | -- | --


An exception occurred: AttributeError: 'NoneType' object has no attribute 'lower'

Traceback (most recent call last):
  File "/opt/netbox/netbox/extras/scripts.py", line 476, in _run_script
    script.output = script.run(data=data, commit=commit)
  File "/opt/netbox/netbox/scripts/NetDoc.py", line 290, in run
    log_ingest(log)
  File "/opt/netbox/venv/lib/python3.10/site-packages/netdoc/utils.py", line 373, in log_ingest
    module.ingest(log)
  File "/opt/netbox/venv/lib/python3.10/site-packages/netdoc/ingestors/netmiko_cisco_nxos_show_lldp_neighbors_detail.py", line 26, in ingest
    remote_interface_label = utils.get_remote_lldp_interface_label(
  File "/opt/netbox/venv/lib/python3.10/site-packages/netdoc/utils.py", line 303, in get_remote_lldp_interface_label
    return normalize_interface_label(port_description)
  File "/opt/netbox/venv/lib/python3.10/site-packages/netdoc/utils.py", line 415, in normalize_interface_label
    name = name.lower()
AttributeError: 'NoneType' object has no attribute 'lower'

```

**Comment by dainok** [comment]
Can you post the parsed JSON log 1455? Or send me via email.

**Comment by mamingzhi945** [comment]
![image](https://github.com/dainok/netdoc/assets/84170304/4786789c-ea01-4104-aa0c-1fc05607863d)

I think the error started from Eth1/7？

**Comment by dainok** [comment]
Can you post also the relevant lines of the parsed JSON file? I'm looking for a `None` value. Usually empty values are empty strings `""`, not `None`.

**Comment by mamingzhi945** [comment]
I sent an email. andrea.dainese@pm.me
