### ISSUE TITLE
Permission denied: '/opt/netbox/nornir.log' on every discovery?

### ISSUE THREAD

**Issue by amdei** [dainok/netdoc#4]
Just installed latest netbox and netdoc.
Added new discovery without any result.
Seen in logs following:
```
Sep 10 20:18:52 ng-netdoc systemd[1]: Started NetBox Request Queue Worker.
Sep 10 20:45:38 ng-netdoc python3[35092]: Traceback (most recent call last):
Sep 10 20:45:38 ng-netdoc python3[35092]:   File "/opt/netbox/venv/lib/python3.9/site-packages/rq/worker.py", line 1068, in perform_job
Sep 10 20:45:38 ng-netdoc python3[35092]:     rv = job.perform()
Sep 10 20:45:38 ng-netdoc python3[35092]:   File "/opt/netbox/venv/lib/python3.9/site-packages/rq/job.py", line 847, in perform
Sep 10 20:45:38 ng-netdoc python3[35092]:     self._result = self._execute()
Sep 10 20:45:38 ng-netdoc python3[35092]:   File "/opt/netbox/venv/lib/python3.9/site-packages/rq/job.py", line 870, in _execute
Sep 10 20:45:38 ng-netdoc python3[35092]:     result = self.func(*self.args, **self.kwargs)
Sep 10 20:45:38 ng-netdoc python3[35092]:   File "/opt/netbox/venv/lib/python3.9/site-packages/netdoc/tasks.py", line 23, in discovery
Sep 10 20:45:38 ng-netdoc python3[35092]:     fh = logging.FileHandler("nornir.log")
Sep 10 20:45:38 ng-netdoc python3[35092]:   File "/usr/lib/python3.9/logging/__init__.py", line 1142, in __init__
Sep 10 20:45:38 ng-netdoc python3[35092]:     StreamHandler.__init__(self, self._open())
Sep 10 20:45:38 ng-netdoc python3[35092]:   File "/usr/lib/python3.9/logging/__init__.py", line 1171, in _open
Sep 10 20:45:38 ng-netdoc python3[35092]:     return open(self.baseFilename, self.mode, encoding=self.encoding,
Sep 10 20:45:38 ng-netdoc python3[35092]: PermissionError: [Errno 13] Permission denied: '/opt/netbox/nornir.log'
```

Was fixed with creating and chown'ing /opt/netbox/nornir.log
But it seems to be inappropriate.

Any clue on how to properly fix this situation?

**Comment by soloduy1** [comment]
I was able to fix it like this:

In file /opt/netbox/venv/lib/python3.8/site-packages/netdoc/tasks.py change 
`fh = logging.FileHandler("nornir.log")`
to
`fh = logging.FileHandler("/opt/netbox/log/nornir.log")`

then create .log file and add netbox:netbox to owners
`touch /opt/netbox/log/nornir.log`
`chown netbox:netbox /opt/netbox/log/nornir.log`

It's works after restart
`systemctl restart netbox netbox-rq`

**Comment by dainok** [comment]
Thank you @soloduy1, I'm including a fix for the next release.
