### ISSUE TITLE
[Issue] IOS parser - show ip interface fails on Async interfaces without IP address

### ISSUE THREAD

**Issue by svestenik** [dainok/netdoc#46]
Netdoc v 0.9.44, fresh install.
While trying to discover a CISCO2901 router running IOS 15.7-3, IOS parser errors out on parsing Async interfaces without IP address.
Traceback from ingest.py script:

Reingesting log 3197 with command show ip interface on device 192.168.143.254 via netmiko_cisco_ios... Traceback (most recent call last):
  File "/opt/netbox/netbox/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/netbox/venv/lib64/python3.9/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
    utility.execute()
  File "/opt/netbox/venv/lib64/python3.9/site-packages/django/core/management/__init__.py", line 440, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/netbox/venv/lib64/python3.9/site-packages/django/core/management/base.py", line 402, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/netbox/venv/lib64/python3.9/site-packages/django/core/management/base.py", line 448, in execute
    output = self.handle(*args, **options)
  File "/opt/netbox/venv/lib64/python3.9/site-packages/django/core/management/commands/shell.py", line 127, in handle
    exec(sys.stdin.read(), globals())
  File "<string>", line 35, in <module>
  File "/opt/netbox/venv/lib64/python3.9/site-packages/netdoc/utils.py", line 237, in log_ingest
    module.ingest(log)
  File "/opt/netbox/venv/lib64/python3.9/site-packages/netdoc/ingestors/netmiko_cisco_ios_show_ip_interface.py", line 53, in ingest
    interface.update_addresses(interface_o, ip_addresses=ip_addresses)
  File "/opt/netbox/venv/lib64/python3.9/site-packages/netdoc/schemas/interface.py", line 263, in update_addresses
    obj.ip_addresses.add(ip_address_o)
  File "/opt/netbox/venv/lib64/python3.9/site-packages/django/contrib/contenttypes/fields.py", line 667, in add
    if obj._state.adding or obj._state.db != db:
AttributeError: 'list' object has no attribute '_state'

[3197.json.log](https://github.com/dainok/ne
[TermServ](https://user-images.githubusercontent.com/33282479/227562895-02dfb1d5-06b6-455a-b738-810c0dfff378.jpg)
tdoc/files/11063589/3197.json.log)

**Comment by dainok** [comment]
I need you post the log in JSON format. You can download it opening the single log in netdoc, and click the export button. Post it here or send it to my email address, as you wish.

**Comment by svestenik** [comment]
Log is actually attached, url got scrambled during upload.

**Comment by dainok** [comment]
Sorry, I missed that.

I think you hit a bug, but it's related to specific data. NetDoc is failing when adding an IP address to a specific interface.
I need your help to debug it, and:

- add a "print(item, ip_addresses)" on /opt/netbox/venv/lib64/python3.9/site-packages/netdoc/ingestors/netmiko_cisco_ios_show_ip_interface.py before line 53
- add a print(ip_address_o) on /opt/netbox/venv/lib64/python3.9/site-packages/netdoc/schemas/interface.py before line 263

Then please check on Netbox how the interface is configured and which IP addresses are attached to.

**Comment by svestenik** [comment]
Updated to latest from Github (v0.9.45) by running " sudo -u netbox /opt/netbox/upgrade.sh" over existing installation before I started the debug. 

Now I have issues with other modules:

Mar 27 14:24:02 python3[451652]: No Netmiko Linux device found
Mar 27 14:24:19 python3[451933]: An exception occurred: `ModuleNotFoundError: Ingestor not found for netmiko_cisco_ios_show_version`
Mar 27 14:24:19 python3[451933]: ```
Mar 27 14:24:19 python3[451933]: Traceback (most recent call last):
Mar 27 14:24:19 python3[451933]:   File "/opt/netbox/venv/lib64/python3.9/site-packages/netdoc/utils.py", line 258, in log_ingest
Mar 27 14:24:19 python3[451933]:     module = importlib.import_module(f"netdoc.ingestors.{function_name}")
Mar 27 14:24:19 python3[451933]:   File "/usr/lib64/python3.9/importlib/__init__.py", line 127, in import_module
Mar 27 14:24:19 python3[451933]:     return _bootstrap._gcd_import(name[level:], package, level)
Mar 27 14:24:19 python3[451933]:   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
Mar 27 14:24:19 python3[451933]:   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
Mar 27 14:24:19 python3[451933]:   File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
Mar 27 14:24:19 python3[451933]: ModuleNotFoundError: No module named 'netdoc.ingestors.netmiko_cisco_ios_show_version'
Mar 27 14:24:19 python3[451933]: The above exception was the direct cause of the following exception:
Mar 27 14:24:19 python3[451933]: Traceback (most recent call last):
Mar 27 14:24:19 python3[451933]:   File "/opt/netbox/netbox/extras/scripts.py", line 464, in _run_script
Mar 27 14:24:19 python3[451933]:     script.output = script.run(data=data, commit=commit)
Mar 27 14:24:19 python3[451933]:   File "/opt/netbox/netbox/scripts/NetDoc.py", line 271, in run
Mar 27 14:24:19 python3[451933]:     log_ingest(log)
Mar 27 14:24:19 python3[451933]:   File "/opt/netbox/venv/lib64/python3.9/site-packages/netdoc/utils.py", line 260, in log_ingest
Mar 27 14:24:19 python3[451933]:     raise ModuleNotFoundError(f"Ingestor not found for {function_name}") from exc
Mar 27 14:24:19 python3[451933]: ModuleNotFoundError: Ingestor not found for netmiko_cisco_ios_show_version
Mar 27 14:24:19 python3[451933]: ```
Mar 27 14:24:19 python3[451933]: Exception raised during script execution: Ingestor not found for netmiko_cisco_ios_show_version
=================================			    
Mar 27 14:52:35 python3[453657]: No Netmiko Linux device found
Mar 27 14:52:52 python3[453935]: An exception occurred: `ModuleNotFoundError: Ingestor not found for netmiko_cisco_ios_show_logging`
Mar 27 14:52:52 python3[453935]: ```
Mar 27 14:52:52 python3[453935]: Traceback (most recent call last):
Mar 27 14:52:52 python3[453935]:   File "/opt/netbox/venv/lib64/python3.9/site-packages/netdoc/utils.py", line 258, in log_ingest
Mar 27 14:52:52 python3[453935]:     module = importlib.import_module(f"netdoc.ingestors.{function_name}")
Mar 27 14:52:52 python3[453935]:   File "/usr/lib64/python3.9/importlib/__init__.py", line 127, in import_module
Mar 27 14:52:52 python3[453935]:     return _bootstrap._gcd_import(name[level:], package, level)
Mar 27 14:52:52 python3[453935]:   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
Mar 27 14:52:52 python3[453935]:   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
Mar 27 14:52:52 python3[453935]:   File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
Mar 27 14:52:52 python3[453935]: ModuleNotFoundError: No module named 'netdoc.ingestors.netmiko_cisco_ios_show_logging'
Mar 27 14:52:52 python3[453935]: The above exception was the direct cause of the following exception:
Mar 27 14:52:52 python3[453935]: Traceback (most recent call last):
Mar 27 14:52:52 python3[453935]:   File "/opt/netbox/netbox/extras/scripts.py", line 464, in _run_script
Mar 27 14:52:52 python3[453935]:     script.output = script.run(data=data, commit=commit)
Mar 27 14:52:52 python3[453935]:   File "/opt/netbox/netbox/scripts/NetDoc.py", line 271, in run
Mar 27 14:52:52 python3[453935]:     log_ingest(log)
Mar 27 14:52:52 python3[453935]:   File "/opt/netbox/venv/lib64/python3.9/site-packages/netdoc/utils.py", line 260, in log_ingest
Mar 27 14:52:52 python3[453935]:     raise ModuleNotFoundError(f"Ingestor not found for {function_name}") from exc
Mar 27 14:52:52 python3[453935]: ModuleNotFoundError: Ingestor not found for netmiko_cisco_ios_show_logging
Mar 27 14:52:52 python3[453935]: ```
Mar 27 14:52:52 python3[453935]: Exception raised during script execution: Ingestor not found for netmiko_cisco_ios_show_logging
================================		    
Mar 27 15:09:29 python3[455214]: An exception occurred: `ModuleNotFoundError: Ingestor not found for netmiko_cisco_ios_show_ip_ospf_neighbor`
Mar 27 15:09:29 python3[455214]: ```
Mar 27 15:09:29 python3[455214]: Traceback (most recent call last):
Mar 27 15:09:29 python3[455214]:   File "/opt/netbox/venv/lib64/python3.9/site-packages/netdoc/utils.py", line 258, in log_ingest
Mar 27 15:09:29 python3[455214]:     module = importlib.import_module(f"netdoc.ingestors.{function_name}")
Mar 27 15:09:29 python3[455214]:   File "/usr/lib64/python3.9/importlib/__init__.py", line 127, in import_module
Mar 27 15:09:29 python3[455214]:     return _bootstrap._gcd_import(name[level:], package, level)
Mar 27 15:09:29 python3[455214]:   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
Mar 27 15:09:29 python3[455214]:   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
Mar 27 15:09:29 python3[455214]:   File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
Mar 27 15:09:29 python3[455214]: ModuleNotFoundError: No module named 'netdoc.ingestors.netmiko_cisco_ios_show_ip_ospf_neighbor'
Mar 27 15:09:29 python3[455214]: The above exception was the direct cause of the following exception:
Mar 27 15:09:29 python3[455214]: Traceback (most recent call last):
Mar 27 15:09:29 python3[455214]:   File "/opt/netbox/netbox/extras/scripts.py", line 464, in _run_script
Mar 27 15:09:29 python3[455214]:     script.output = script.run(data=data, commit=commit)
Mar 27 15:09:29 python3[455214]:   File "/opt/netbox/netbox/scripts/NetDoc.py", line 271, in run
Mar 27 15:09:29 python3[455214]:     log_ingest(log)
Mar 27 15:09:29 python3[455214]:   File "/opt/netbox/venv/lib64/python3.9/site-packages/netdoc/utils.py", line 260, in log_ingest
Mar 27 15:09:29 python3[455214]:     raise ModuleNotFoundError(f"Ingestor not found for {function_name}") from exc
Mar 27 15:09:29 python3[455214]: ModuleNotFoundError: Ingestor not found for netmiko_cisco_ios_show_ip_ospf_neighbor
Mar 27 15:09:29 python3[455214]: ```
================================

**Comment by svestenik** [comment]
Updated to latest from Github (v0.9.45) by running " sudo -u netbox /opt/netbox/upgrade.sh" over existing installation before I started the debug. 

Now I have issues with other modules:
```
Mar 27 14:24:02 python3[451652]: No Netmiko Linux device found
Mar 27 14:24:19 python3[451933]: An exception occurred: `ModuleNotFoundError: Ingestor not found for netmiko_cisco_ios_show_version`
Mar 27 14:24:19 python3[451933]: ```
Mar 27 14:24:19 python3[451933]: Traceback (most recent call last):
Mar 27 14:24:19 python3[451933]:   File "/opt/netbox/venv/lib64/python3.9/site-packages/netdoc/utils.py", line 258, in log_ingest
Mar 27 14:24:19 python3[451933]:     module = importlib.import_module(f"netdoc.ingestors.{function_name}")
Mar 27 14:24:19 python3[451933]:   File "/usr/lib64/python3.9/importlib/__init__.py", line 127, in import_module
Mar 27 14:24:19 python3[451933]:     return _bootstrap._gcd_import(name[level:], package, level)
Mar 27 14:24:19 python3[451933]:   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
Mar 27 14:24:19 python3[451933]:   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
Mar 27 14:24:19 python3[451933]:   File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
Mar 27 14:24:19 python3[451933]: ModuleNotFoundError: No module named 'netdoc.ingestors.netmiko_cisco_ios_show_version'
Mar 27 14:24:19 python3[451933]: The above exception was the direct cause of the following exception:
Mar 27 14:24:19 python3[451933]: Traceback (most recent call last):
Mar 27 14:24:19 python3[451933]:   File "/opt/netbox/netbox/extras/scripts.py", line 464, in _run_script
Mar 27 14:24:19 python3[451933]:     script.output = script.run(data=data, commit=commit)
Mar 27 14:24:19 python3[451933]:   File "/opt/netbox/netbox/scripts/NetDoc.py", line 271, in run
Mar 27 14:24:19 python3[451933]:     log_ingest(log)
Mar 27 14:24:19 python3[451933]:   File "/opt/netbox/venv/lib64/python3.9/site-packages/netdoc/utils.py", line 260, in log_ingest
Mar 27 14:24:19 python3[451933]:     raise ModuleNotFoundError(f"Ingestor not found for {function_name}") from exc
Mar 27 14:24:19 python3[451933]: ModuleNotFoundError: Ingestor not found for netmiko_cisco_ios_show_version
Mar 27 14:24:19 python3[451933]: ```
Mar 27 14:24:19 python3[451933]: Exception raised during script execution: Ingestor not found for netmiko_cisco_ios_show_version
=================================			    
Mar 27 14:52:35 python3[453657]: No Netmiko Linux device found
Mar 27 14:52:52 python3[453935]: An exception occurred: `ModuleNotFoundError: Ingestor not found for netmiko_cisco_ios_show_logging`
Mar 27 14:52:52 python3[453935]: ```
Mar 27 14:52:52 python3[453935]: Traceback (most recent call last):
Mar 27 14:52:52 python3[453935]:   File "/opt/netbox/venv/lib64/python3.9/site-packages/netdoc/utils.py", line 258, in log_ingest
Mar 27 14:52:52 python3[453935]:     module = importlib.import_module(f"netdoc.ingestors.{function_name}")
Mar 27 14:52:52 python3[453935]:   File "/usr/lib64/python3.9/importlib/__init__.py", line 127, in import_module
Mar 27 14:52:52 python3[453935]:     return _bootstrap._gcd_import(name[level:], package, level)
Mar 27 14:52:52 python3[453935]:   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
Mar 27 14:52:52 python3[453935]:   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
Mar 27 14:52:52 python3[453935]:   File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
Mar 27 14:52:52 python3[453935]: ModuleNotFoundError: No module named 'netdoc.ingestors.netmiko_cisco_ios_show_logging'
Mar 27 14:52:52 python3[453935]: The above exception was the direct cause of the following exception:
Mar 27 14:52:52 python3[453935]: Traceback (most recent call last):
Mar 27 14:52:52 python3[453935]:   File "/opt/netbox/netbox/extras/scripts.py", line 464, in _run_script
Mar 27 14:52:52 python3[453935]:     script.output = script.run(data=data, commit=commit)
Mar 27 14:52:52 python3[453935]:   File "/opt/netbox/netbox/scripts/NetDoc.py", line 271, in run
Mar 27 14:52:52 python3[453935]:     log_ingest(log)
Mar 27 14:52:52 python3[453935]:   File "/opt/netbox/venv/lib64/python3.9/site-packages/netdoc/utils.py", line 260, in log_ingest
Mar 27 14:52:52 python3[453935]:     raise ModuleNotFoundError(f"Ingestor not found for {function_name}") from exc
Mar 27 14:52:52 python3[453935]: ModuleNotFoundError: Ingestor not found for netmiko_cisco_ios_show_logging
Mar 27 14:52:52 python3[453935]: ```
Mar 27 14:52:52 python3[453935]: Exception raised during script execution: Ingestor not found for netmiko_cisco_ios_show_logging
================================		    
Mar 27 15:09:29 python3[455214]: An exception occurred: `ModuleNotFoundError: Ingestor not found for netmiko_cisco_ios_show_ip_ospf_neighbor`
Mar 27 15:09:29 python3[455214]: ```
Mar 27 15:09:29 python3[455214]: Traceback (most recent call last):
Mar 27 15:09:29 python3[455214]:   File "/opt/netbox/venv/lib64/python3.9/site-packages/netdoc/utils.py", line 258, in log_ingest
Mar 27 15:09:29 python3[455214]:     module = importlib.import_module(f"netdoc.ingestors.{function_name}")
Mar 27 15:09:29 python3[455214]:   File "/usr/lib64/python3.9/importlib/__init__.py", line 127, in import_module
Mar 27 15:09:29 python3[455214]:     return _bootstrap._gcd_import(name[level:], package, level)
Mar 27 15:09:29 python3[455214]:   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
Mar 27 15:09:29 python3[455214]:   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
Mar 27 15:09:29 python3[455214]:   File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
Mar 27 15:09:29 python3[455214]: ModuleNotFoundError: No module named 'netdoc.ingestors.netmiko_cisco_ios_show_ip_ospf_neighbor'
Mar 27 15:09:29 python3[455214]: The above exception was the direct cause of the following exception:
Mar 27 15:09:29 python3[455214]: Traceback (most recent call last):
Mar 27 15:09:29 python3[455214]:   File "/opt/netbox/netbox/extras/scripts.py", line 464, in _run_script
Mar 27 15:09:29 python3[455214]:     script.output = script.run(data=data, commit=commit)
Mar 27 15:09:29 python3[455214]:   File "/opt/netbox/netbox/scripts/NetDoc.py", line 271, in run
Mar 27 15:09:29 python3[455214]:     log_ingest(log)
Mar 27 15:09:29 python3[455214]:   File "/opt/netbox/venv/lib64/python3.9/site-packages/netdoc/utils.py", line 260, in log_ingest
Mar 27 15:09:29 python3[455214]:     raise ModuleNotFoundError(f"Ingestor not found for {function_name}") from exc
Mar 27 15:09:29 python3[455214]: ModuleNotFoundError: Ingestor not found for netmiko_cisco_ios_show_ip_ospf_neighbor
Mar 27 15:09:29 python3[455214]: ```
================================
```
