### ISSUE TITLE
No parse or ingest 

### ISSUE THREAD

**Issue by nikor30** [dainok/netdoc#5]
Netbox (v3.3.2)

Hi hope you can help :-)

All logs look good.

![image](https://user-images.githubusercontent.com/4319444/190686421-90113173-971b-46cc-bb38-4885f07c192f.png)

**Comment by dainok** [comment]
No, it doesn't. netdoc is in alpha version, it means that you must be able to debug. Read the debug section in the readme file (https://github.com/dainok/netdoc) and open a new issue with details.

Otherwise sponsor the project choosing the option with the support included.

**Comment by dainok** [comment]
Insufficient details.

**Comment by nikor30** [comment]
Okay, so I am not a developer so debugging skills are limited :-)

So I can only help with some guidance, and support with some cases which could help to refine the plugin.

If you tell me what logs you need and how to get them, I can help.

Regards Niko

**Comment by dainok** [comment]
Please check:
- if at least one log has been parsed
- if you start the discovery again you have the same result (no parsing at all)

**Comment by nikor30** [comment]
So tried to delte and discover several times again but same result 

here some striped down output from journalctl -u netbox-rq -f 

```
Sep 20 06:58:17 sdegilvnetbx2dev python3[2551999]: ^^^^ END additional_tasks ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Sep 20 06:58:17 sdegilvnetbx2dev python3[2551999]: Task 'multiple_tasks' has not been run – 0 hosts selected
Sep 20 06:58:17 sdegilvnetbx2dev python3[2551999]: multiple_tasks******************************************************************
Sep 20 06:58:17 sdegilvnetbx2dev python3[2551999]: Task 'multiple_tasks' has not been run – 0 hosts selected
Sep 20 06:58:17 sdegilvnetbx2dev python3[2551999]: multiple_tasks******************************************************************
Sep 20 06:58:40 sdegilvnetbx2dev python3[2552024]: {'data': {'dry_run': False, 'failed_hosts': set()},
Sep 20 06:58:40 sdegilvnetbx2dev python3[2552024]:  'inventory': {'defaults': {'connection_options': {},
Sep 20 06:58:40 sdegilvnetbx2dev python3[2552024]:                             'data': {},
Sep 20 06:58:40 sdegilvnetbx2dev python3[2552024]:                             'hostname': None,
Sep 20 06:58:40 sdegilvnetbx2dev python3[2552024]:                             'password': None,
Sep 20 06:58:40 sdegilvnetbx2dev python3[2552024]:                             'platform': None,
Sep 20 06:58:40 sdegilvnetbx2dev python3[2552024]:                             'port': None,
Sep 20 06:58:40 sdegilvnetbx2dev python3[2552024]:                             'username': None},
Sep 20 06:58:40 sdegilvnetbx2dev python3[2552024]:                'groups': {'all': {'connection_options': {},
Sep 20 06:58:40 sdegilvnetbx2dev python3[2552024]:                                   'data': {},
Sep 20 06:58:40 sdegilvnetbx2dev python3[2552024]:                                   'groups': [],
Sep 20 06:58:40 sdegilvnetbx2dev python3[2552024]:                                   'hostname': None,
Sep 20 06:58:40 sdegilvnetbx2dev python3[2552024]:                                   'name': 'all',
Sep 20 06:58:40 sdegilvnetbx2dev python3[2552024]:                                   'password': None,
Sep 20 06:58:40 sdegilvnetbx2dev python3[2552024]:                                   'platform': None,
Sep 20 06:58:40 sdegilvnetbx2dev python3[2552024]:                                   'port': None,
Sep 20 06:58:40 sdegilvnetbx2dev python3[2552024]:                                   'username': None},
Sep 20 06:58:40 sdegilvnetbx2dev python3[2552024]:                           'cisco_ios': {'connection_options': {},
Sep 20 06:58:40 sdegilvnetbx2dev python3[2552024]:                                         'data': {},
Sep 20 06:58:40 sdegilvnetbx2dev python3[2552024]:                                         'groups': [],
Sep 20 06:58:40 sdegilvnetbx2dev python3[2552024]:                                         'hostname': None,
Sep 20 06:58:40 sdegilvnetbx2dev python3[2552024]:                                         'name': 'cisco_ios',
Sep 20 06:58:40 sdegilvnetbx2dev python3[2552024]:                                         'password': None,
Sep 20 06:58:40 sdegilvnetbx2dev python3[2552024]:                                         'platform': None,
Sep 20 06:58:40 sdegilvnetbx2dev python3[2552024]:                                         'port': None,
Sep 20 06:58:40 sdegilvnetbx2dev python3[2552024]:                                         'username': None},
Sep 20 06:58:40 sdegilvnetbx2dev python3[2552024]:                           'site-eqx': {'connection_options': {},
Sep 20 06:58:40 sdegilvnetbx2dev python3[2552024]:                                        'data': {},
Sep 20 06:58:40 sdegilvnetbx2dev python3[2552024]:                                        'groups': [],
Sep 20 06:58:40 sdegilvnetbx2dev python3[2552024]:                                        'hostname': None,
Sep 20 06:58:40 sdegilvnetbx2dev python3[2552024]:                                        'name': 'site-eqx',
Sep 20 06:58:40 sdegilvnetbx2dev python3[2552024]:                                        'password': None,
Sep 20 06:58:40 sdegilvnetbx2dev python3[2552024]:                                        'platform': None,
Sep 20 06:58:40 sdegilvnetbx2dev python3[2552024]:                                        'port': None,
Sep 20 06:58:40 sdegilvnetbx2dev python3[2552024]:                                        'username': None}},
Sep 20 06:58:40 sdegilvnetbx2dev python3[2552024]:                'hosts': {'172.20.10.1': {'connection_options': {},
Sep 20 06:58:40 sdegilvnetbx2dev python3[2552024]:                                          'data': {'site': 'eqx', 'site_id': 2},
Sep 20 06:58:40 sdegilvnetbx2dev python3[2552024]:                                          'groups': ['cisco_ios', 'site-eqx'],
Sep 20 06:58:40 sdegilvnetbx2dev python3[2552024]:                                          'hostname': '172.20.10.1',
Sep 20 06:58:40 sdegilvnetbx2dev python3[2552024]:                                          'name': '172.20.10.1',
Sep 20 06:58:40 sdegilvnetbx2dev python3[2552024]:                                          'password': 'password',
Sep 20 06:58:40 sdegilvnetbx2dev python3[2552024]:                                          'platform': 'cisco_ios',
Sep 20 06:58:40 sdegilvnetbx2dev python3[2552024]:                                          'port': 22,
Sep 20 06:58:40 sdegilvnetbx2dev python3[2552024]:                                          'username': 'user'}}}}
Sep 20 06:58:49 sdegilvnetbx2dev python3[2552024]: multiple_tasks******************************************************************
Sep 20 06:58:49 sdegilvnetbx2dev python3[2552024]: * 172.20.10.1 ** changed : False ***********************************************
Sep 20 06:58:49 sdegilvnetbx2dev python3[2552024]: vvvv multiple_tasks ** changed : False vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv INFO
Sep 20 06:58:49 sdegilvnetbx2dev python3[2552024]: ---- show running-config ** changed : False ------------------------------------ INFO
Sep 20 06:58:49 sdegilvnetbx2dev python3[2552024]: Building configuration...
Sep 20 06:58:49 sdegilvnetbx2dev python3[2552024]: Current configuration : 88168 bytes
Sep 20 06:58:49 sdegilvnetbx2dev python3[2552024]: !
Sep 20 06:58:49 sdegilvnetbx2dev python3[2552024]: ! Last configuration change at 15:48:01 CET Fri Sep 16 2022 by surs
Sep 20 06:58:49 sdegilvnetbx2dev python3[2552024]: ! NVRAM config last updated at 15:48:02 CET Fri Sep 16 2022 by surs
Sep 20 06:58:49 sdegilvnetbx2dev python3[2552024]: !
Sep 20 06:58:49 sdegilvnetbx2dev python3[2552024]: version 15.2
Sep 20 06:58:49 sdegilvnetbx2dev python3[2552024]: service timestamps debug datetime msec localtime show-timezone
Sep 20 06:58:49 sdegilvnetbx2dev python3[2552024]: service timestamps log datetime msec localtime show-timezone
Sep 20 06:58:49 sdegilvnetbx2dev python3[2552024]: service password-encryption
Sep 20 06:58:49 sdegilvnetbx2dev python3[2552024]: service counters max age 5
Sep 20 06:58:49 sdegilvnetbx2dev python3[2552024]: !
Sep 20 06:58:49 sdegilvnetbx2dev python3[2552024]: hostname SSTO001CORE_VSS
.
.
.
Sep 20 06:58:50 sdegilvnetbx2dev python3[2552024]: ---- show version ** changed : False ------------------------------------------- INFO
Sep 20 06:58:50 sdegilvnetbx2dev python3[2552024]: Cisco IOS Software, s2t54 Software (s2t54-IPSERVICESK9-M), Version 15.2(1)SY4, RELEASE SOFTWARE (fc4)
Sep 20 06:58:50 sdegilvnetbx2dev python3[2552024]: Technical Support: http://www.cisco.com/techsupport
Sep 20 06:58:50 sdegilvnetbx2dev python3[2552024]: Copyright (c) 1986-2017 by Cisco Systems, Inc.
Sep 20 06:58:50 sdegilvnetbx2dev python3[2552024]: Compiled Mon 10-Apr-17 14:56 by prod_rel_team
Sep 20 06:58:50 sdegilvnetbx2dev python3[2552024]: ROM: System Bootstrap, Version 12.2(50r)SYS3, RELEASE SOFTWARE (fc1)
Sep 20 06:58:50 sdegilvnetbx2dev python3[2552024]: SSTO001CORE_VSS uptime is 5 years, 3 weeks, 4 days, 21 hours, 30 minutes
Sep 20 06:58:50 sdegilvnetbx2dev python3[2552024]: Uptime for this control processor is 3 years, 28 weeks, 2 days, 1 hour, 22 minutes
Sep 20 06:58:50 sdegilvnetbx2dev python3[2552024]: System returned to ROM by reload
Sep 20 06:58:50 sdegilvnetbx2dev python3[2552024]: System restarted at 06:36:01 CET Thu Mar 7 2019
Sep 20 06:58:50 sdegilvnetbx2dev python3[2552024]: System image file is "bootdisk:s2t54-ipservicesk9-mz.SPA.152-1.SY4.bin"
Sep 20 06:58:50 sdegilvnetbx2dev python3[2552024]: Last reload reason: power-on
Sep 20 06:58:50 sdegilvnetbx2dev python3[2552024]: This product contains cryptographic features and is subject to United
Sep 20 06:58:50 sdegilvnetbx2dev python3[2552024]: States and local country laws governing import, export, transfer and
Sep 20 06:58:50 sdegilvnetbx2dev python3[2552024]: use. Delivery of Cisco cryptographic products does not imply
Sep 20 06:58:50 sdegilvnetbx2dev python3[2552024]: third-party authority to import, export, distribute or use encryption.
Sep 20 06:58:50 sdegilvnetbx2dev python3[2552024]: Importers, exporters, distributors and users are responsible for
Sep 20 06:58:50 sdegilvnetbx2dev python3[2552024]: compliance with U.S. and local country laws. By using this product you
Sep 20 06:58:50 sdegilvnetbx2dev python3[2552024]: agree to comply with applicable laws and regulations. If you are unable
Sep 20 06:58:50 sdegilvnetbx2dev python3[2552024]: to comply with U.S. and local laws, return this product immediately.
Sep 20 06:58:50 sdegilvnetbx2dev python3[2552024]: A summary of U.S. laws governing Cisco cryptographic products may be found at:
Sep 20 06:58:50 sdegilvnetbx2dev python3[2552024]: http://www.cisco.com/wwl/export/crypto/tool/stqrg.html
Sep 20 06:58:50 sdegilvnetbx2dev python3[2552024]: If you require further assistance please contact us by sending email to
Sep 20 06:58:50 sdegilvnetbx2dev python3[2552024]: export@cisco.com.
Sep 20 06:58:50 sdegilvnetbx2dev python3[2552024]: cisco WS-C6506-E (M8572) processor (revision ) with 1785856K/262144K bytes of memory.
Sep 20 06:58:50 sdegilvnetbx2dev python3[2552024]: Processor board ID SAL1206FY27
Sep 20 06:58:50 sdegilvnetbx2dev python3[2552024]:  CPU: MPC8572_E, Version: 2.2, (0x80E80022)
Sep 20 06:58:50 sdegilvnetbx2dev python3[2552024]:  CORE: E500, Version: 3.0, (0x80210030)
Sep 20 06:58:50 sdegilvnetbx2dev python3[2552024]:  CPU:1500MHz, CCB:600MHz, DDR:600MHz
Sep 20 06:58:50 sdegilvnetbx2dev python3[2552024]:  L1:    D-cache 32 kB enabled
Sep 20 06:58:50 sdegilvnetbx2dev python3[2552024]:         I-cache 32 kB enabled
Sep 20 06:58:50 sdegilvnetbx2dev python3[2552024]: Last reset from power-on
Sep 20 06:58:50 sdegilvnetbx2dev python3[2552024]: 146 Virtual Ethernet interfaces
Sep 20 06:58:50 sdegilvnetbx2dev python3[2552024]: 54 Gigabit Ethernet interfaces
Sep 20 06:58:50 sdegilvnetbx2dev python3[2552024]: 84 Ten Gigabit Ethernet interfaces
Sep 20 06:58:50 sdegilvnetbx2dev python3[2552024]: 2543K bytes of non-volatile configuration memory.
Sep 20 06:58:50 sdegilvnetbx2dev python3[2552024]: Configuration register is 0x2102
Sep 20 06:58:50 sdegilvnetbx2dev python3[2552024]: ---- show logging ** changed : False ------------------------------------------- INFO
.
.
.
.
Sep 20 06:58:54 sdegilvnetbx2dev python3[2552024]: ^^^^ END additional_tasks ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Sep 20 06:58:54 sdegilvnetbx2dev python3[2552024]: Task 'multiple_tasks' has not been run – 0 hosts selected
Sep 20 06:58:54 sdegilvnetbx2dev python3[2552024]: multiple_tasks******************************************************************
Sep 20 06:58:54 sdegilvnetbx2dev python3[2552024]: Task 'multiple_tasks' has not been run – 0 hosts selected
Sep 20 06:58:54 sdegilvnetbx2dev python3[2552024]: multiple_tasks**
```

**Comment by dainok** [comment]
Try this:
- load your Python environment: source /opt/netbox/venv/bin/activate
- load the shell: python /opt/netbox/netbox/manage.py shell
- paste the following:

~~~
from netdoc import models
import importlib
from netdoc import functions
import logging
import pprint

logs = models.DiscoveryLog.objects.all()
logs = logs.filter(success=True)

for log in logs:
    functions.log_parse(log)
    print('Parsed:', log.parsed)
    print('Items:', len(log.parsed_output))
~~~

You need to adjust paths based on your setup.

**Comment by nikor30** [comment]
Hi this is what I get as a result.

My path is /opt/netbox/

```
venv) root@sdegilvnetbx2dev:~# python /opt/netbox/netbox/manage.py shell
Python 3.8.10 (default, Jun 22 2022, 20:18:18) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> from netdoc import models
>>> import importlib
>>> from netdoc import functions
>>> import logging
>>> import pprint
>>> 
>>> logs = models.DiscoveryLog.objects.all()
>>> logs = logs.filter(success=True)
>>> 
>>> for log in logs:
...     functions.log_parse(log)
...     print('Parsed:', log.parsed)
...     print('Items:', len(log.parsed_output))
... 
Traceback (most recent call last):
  File "/opt/netbox-3.3.2/venv/lib/python3.8/site-packages/netdoc/functions.py", line 102, in parse_netmiko_output
    parsed_output = get_structured_data(output, platform=platform, command=command)
  File "/opt/netbox-3.3.2/venv/lib/python3.8/site-packages/netmiko/utilities.py", line 344, in get_structured_data
    template_dir = get_template_dir()
  File "/opt/netbox-3.3.2/venv/lib/python3.8/site-packages/netmiko/utilities.py", line 297, in get_template_dir
    raise ValueError(msg)
ValueError: 
Directory containing TextFSM index file not found.

Please set the NET_TEXTFSM environment variable to point at the directory containing your TextFSM
index file.

Alternatively, `pip install ntc-templates` (if using ntc-templates).



During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<console>", line 2, in <module>
  File "/opt/netbox-3.3.2/venv/lib/python3.8/site-packages/netdoc/functions.py", line 89, in log_parse
    parsed_output = parse_netmiko_output(log.raw_output, platform=platform, command=log.request)
  File "/opt/netbox-3.3.2/venv/lib/python3.8/site-packages/netdoc/functions.py", line 106, in parse_netmiko_output
    raise FailedToParse
netdoc.functions.FailedToParse
```

**Comment by dainok** [comment]
You missed an important step during the initial setup. Read carefully https://github.com/dainok/netdoc

**Comment by nikor30** [comment]
```
(venv) root@sdegilvnetbx2dev:~# vi /opt/netbox-3.3.2/venv/lib/python3.8/site-packages/netdoc/functions.py  
(venv) root@sdegilvnetbx2dev:~# pip install netmiko
Requirement already satisfied: netmiko in /opt/netbox-3.3.2/venv/lib/python3.8/site-packages (3.4.0)
Requirement already satisfied: scp>=0.13.2 in /opt/netbox-3.3.2/venv/lib/python3.8/site-packages (from netmiko) (0.14.4)
Requirement already satisfied: paramiko>=2.6.0 in /opt/netbox-3.3.2/venv/lib/python3.8/site-packages (from netmiko) (2.11.0)
Requirement already satisfied: setuptools>=38.4.0 in /opt/netbox-3.3.2/venv/lib/python3.8/site-packages (from netmiko) (44.0.0)
Requirement already satisfied: ntc-templates in /opt/netbox-3.3.2/venv/lib/python3.8/site-packages (from netmiko) (3.1.0)
Requirement already satisfied: pyserial in /opt/netbox-3.3.2/venv/lib/python3.8/site-packages (from netmiko) (3.5)
Requirement already satisfied: tenacity in /opt/netbox-3.3.2/venv/lib/python3.8/site-packages (from netmiko) (8.0.1)
Requirement already satisfied: six in /opt/netbox-3.3.2/venv/lib/python3.8/site-packages (from paramiko>=2.6.0->netmiko) (1.16.0)
Requirement already satisfied: bcrypt>=3.1.3 in /opt/netbox-3.3.2/venv/lib/python3.8/site-packages (from paramiko>=2.6.0->netmiko) (4.0.0)
Requirement already satisfied: cryptography>=2.5 in /opt/netbox-3.3.2/venv/lib/python3.8/site-packages (from paramiko>=2.6.0->netmiko) (38.0.1)
Requirement already satisfied: pynacl>=1.0.1 in /opt/netbox-3.3.2/venv/lib/python3.8/site-packages (from paramiko>=2.6.0->netmiko) (1.5.0)
Requirement already satisfied: textfsm<2.0.0,>=1.1.0 in /opt/netbox-3.3.2/venv/lib/python3.8/site-packages (from ntc-templates->netmiko) (1.1.3)
Requirement already satisfied: cffi>=1.12 in /opt/netbox-3.3.2/venv/lib/python3.8/site-packages (from cryptography>=2.5->paramiko>=2.6.0->netmiko) (1.15.1)
Requirement already satisfied: future in /opt/netbox-3.3.2/venv/lib/python3.8/site-packages (from textfsm<2.0.0,>=1.1.0->ntc-templates->netmiko) (0.18.2)
Requirement already satisfied: pycparser in /opt/netbox-3.3.2/venv/lib/python3.8/site-packages (from cffi>=1.12->cryptography>=2.5->paramiko>=2.6.0->netmiko) (2.21)

```

**Comment by dainok** [comment]
Not an issue.

**Comment by dainok** [comment]
Not an issue

**Comment by nikor30** [comment]
Let me guess...

`git clone --depth=1 https://github.com/networktocode/ntc-templates /opt/ntc-templates`

Now it´s importing :-)

**Comment by nikor30** [comment]
Thanks for your help :-)

**Comment by dainok** [comment]
I'm curious: the python exception wasn't reported by journalctl?

**Comment by nikor30** [comment]
No it was not didn't see it in any of the outputs
