### ISSUE TITLE
Cisco IOS: Issue with ingesting IP addresses

### ISSUE THREAD

**Issue by svestenik** [dainok/netdoc#56]
Hi,
after latest upgrade from github, issue with ingesting IP addresses is popping up everywhere:

```
An exception occurred: TypeError: 'NoneType' object is not iterable

Traceback (most recent call last):
  File "/opt/netbox/netbox/extras/scripts.py", line 476, in _run_script
    script.output = script.run(data=data, commit=commit)
  File "/opt/netbox/netbox/scripts/NetDoc.py", line 290, in run
    log_ingest(log)
  File "/opt/netbox/venv/lib/python3.9/site-packages/netdoc/utils.py", line 505, in log_ingest
    module.ingest(log)
  File "/opt/netbox/venv/lib/python3.9/site-packages/netdoc/ingestors/netmiko_cisco_ios_show_ip_interface.py", line 26, in ingest
    f"{ipaddr}/{mask_list[index]}" for index, ipaddr in enumerate(ip_list)
TypeError: 'NoneType' object is not iterable
```

Log file attached:
[20582.json.txt](https://github.com/dainok/netdoc/files/12368562/20582.json.txt)

Same issue affects several IOS platforms:
- ASR 1002 (IOS-XE Version 15.5(3)S6b)
- Cisco 2911 router (Version 15.0(1r)M16)

**Comment by dainok** [comment]
I reviewed all templates (except IOS and Comware), test 0.10.27.
Let me know if you still have issues.
