### ISSUE TITLE
Compatibility with NetBox 3.5

### ISSUE THREAD

**Issue by uvinva** [dainok/netdoc#8]
I have a problem installing. Netbox 3.5.3

Applying database migrations (python3 netbox/manage.py migrate)...
Traceback (most recent call last):
  File "netbox/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
    utility.execute()
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 420, in execute
    django.setup()
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/apps/registry.py", line 116, in populate
    app_config.import_models()
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/apps/config.py", line 269, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/netbox/venv/lib/python3.8/site-packages/netdoc/models.py", line 24, in <module>
    from netdoc.utils import parse_netmiko_output, CONFIG_COMMANDS, FAILURE_OUTPUT
  File "/opt/netbox/venv/lib/python3.8/site-packages/netdoc/utils.py", line 29, in <module>
    from extras.scripts import get_scripts, run_script
ImportError: cannot import name 'get_scripts' from 'extras.scripts' (/opt/netbox/netbox/extras/scripts.py)

**Comment by dainok** [comment]
Which NetBox version are you using? I tested until 3.4.10.

**Comment by uvinva** [comment]
> Which NetBox version are you using? I tested until 3.4.10.
> 
> 

I tested on latest version 3.5.3

**Comment by dainok** [comment]
I think that's the issue. Please try again with 3.4.10 and let me know.

**Comment by paddsen** [comment]
The script model has changed substantially for netbox 3.5.x. I was able to work around the initial get_script and JobResult errors, but now struggling with ingestion.

**Comment by dainok** [comment]
I'm working on https://github.com/dainok/netdoc/pull/68

@uvinva @paddsen if you have time, please test on a separate instance. It's working on my side, but I would like to have more feedback, installing from scratch and upgrading an existing instance.

**Comment by cmong-nextech** [comment]
I am having this issue on Netbox version 3.6.1 as well. Here's the traceback:

Applying database migrations (python3 netbox/manage.py migrate)...
Traceback (most recent call last):
  File "/opt/netbox/netbox/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/netbox/venv/lib/python3.9/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/opt/netbox/venv/lib/python3.9/site-packages/django/core/management/__init__.py", line 416, in execute
    django.setup()
  File "/opt/netbox/venv/lib/python3.9/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/opt/netbox/venv/lib/python3.9/site-packages/django/apps/registry.py", line 116, in populate
    app_config.import_models()
  File "/opt/netbox/venv/lib/python3.9/site-packages/django/apps/config.py", line 269, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/netbox/venv/lib/python3.9/site-packages/netdoc/models.py", line 30, in <module>
    from netdoc.utils import (
  File "/opt/netbox/venv/lib/python3.9/site-packages/netdoc/utils.py", line 29, in <module>
    from extras.scripts import get_scripts, run_script
ImportError: cannot import name 'get_scripts' from 'extras.scripts' (/opt/netbox/netbox/extras/scripts.py)

**Comment by dainok** [comment]
Fixed with https://github.com/dainok/netdoc/pull/68
Note: NetBox 3.4 is not supported anymore.
