### ISSUE TITLE
PaloAlto - "An exception occurred: AttributeError: 'NoneType' object has no attribute 'lower'"

### ISSUE THREAD

**Issue by proebstle** [dainok/netdoc#86]
An exception occurred: AttributeError: 'NoneType' object has no attribute 'lower'

Traceback (most recent call last):
  File "/opt/netbox-3.5.9/netbox/extras/scripts.py", line 504, in _run_script
    script.output = script.run(data=data, commit=commit)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/netbox-3.5.9/netbox/scripts/netdoc_scripts.py", line 353, in run
    log_ingest(log)
  File "/opt/netbox/venv/lib/python3.11/site-packages/netdoc/utils.py", line 578, in log_ingest
    module.ingest(log)
  File "/opt/netbox/venv/lib/python3.11/site-packages/netdoc/ingestors/xml_panw_ngfw_show_routing_route.py", line 78, in ingest
    nexthop_if_label = utils.normalize_interface_label(nexthop_if_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/netbox/venv/lib/python3.11/site-packages/netdoc/utils.py", line 636, in normalize_interface_label
    name = name.lower().strip()
           ^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'lower'

**Comment by dainok** [comment]
Fixed by https://github.com/dainok/netdoc/pull/85

**Comment by proebstle** [comment]
Great work! 
   
  
      
   
  
    I will add more devices and check importet data next week :-) 
   
  
      
   
  
    Now only missing ArubaCX :-) 
   
  
      
   
   
    
   
   
   
     Andrea Dainese ***@***.***> hat am 08.10.2023 15:43 CEST geschrieben: 
    
   
       
    
   
       
    
   
     Fixed by https://github.com/dainok/netdoc/pull/85

**Comment by proebstle** [comment]
Done
